import { describe, it, expect } from 'vitest'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { resolve, join } from 'node:path'

/**
 * Workspace-broker verb registry — the check that keeps F3 closed.
 *
 * THE FINDING. Nothing enumerated the broker's verb set. `handle()` in
 * `operator/workspace_broker/server.py` dispatches on bare string literals
 * (`if action == "job_claim":` …), 32 of them, and a verb could be added or
 * removed with no signal anywhere.
 *
 * WHY THAT MATTERS HERE SPECIFICALLY. Each verb is a uid-gated door into the
 * append-only audit log, and the broker's whole discipline is that a WRITING
 * verb pins exactly one `action_type` so it cannot forge another verb's row
 * (see the comments around `suppressed_wake_append` and `emitted_wake_append`).
 * That discipline is per-verb by construction: it holds only for verbs someone
 * looked at. An unenumerated surface is one where "someone looked at all of
 * them" is not a checkable claim.
 *
 * TWO ASSERTIONS, AND AN HONEST ONE ABOUT COVERAGE.
 *
 *   1. The verb set equals the contract. Adding or removing a verb is a
 *      conscious act that shows up in a reviewable diff, not a side effect of
 *      an edit to a 2,000-line dispatcher.
 *
 *   2. Every verb is NAMED somewhere in the broker's own test suite, except
 *      for an exemption list that may only SHRINK.
 *
 * On (2): being named in a test file is a weak proxy for being tested, and
 * this file does not claim otherwise. It catches exactly one thing — a brand
 * new verb shipping with no test that so much as mentions it — which is the
 * case that actually occurs. Five verbs are exempt because they are in that
 * state TODAY (`health`, `job_cancel`, `job_heartbeat`, `job_list`,
 * `job_list_claimable`); pinning the debt at five and making six impossible is
 * a real gate, where blocking this PR on writing five tests would have been a
 * different piece of work wearing this one's clothes.
 *
 * WHAT WOULD MAKE THIS FALSE (Law 12). Add a verb to `handle()` and the
 * registry test goes red. Remove one and it goes red. Add a verb without a
 * test mention and the coverage test goes red naming it. Break the extractor
 * so it finds nothing and the self-test goes red — an empty verb set would
 * otherwise satisfy "every verb is tested" vacuously.
 */

const REPO_ROOT = resolve(__dirname, '..')
const SERVER = join(REPO_ROOT, 'operator', 'workspace_broker', 'server.py')
const TESTS_DIR = join(REPO_ROOT, 'operator', 'workspace_broker', 'tests')

/**
 * The broker's dispatch verbs, in sorted order.
 *
 * Kept as a literal list rather than a generated JSON contract: at 32 entries
 * it is readable in a diff, and the point of the gate is that a reviewer SEES
 * the verb being added. A generated artifact would be regenerated by the same
 * commit that adds the verb and would show the reviewer nothing they had to
 * think about.
 */
const EXPECTED_VERBS = [
  'act_commit',
  'act_propose',
  'audit_append',
  'authorize',
  'correction_propose',
  'emitted_wake_append',
  'escalation_event_append',
  'establish_decline',
  'establish_lapse_notified',
  'establish_notify_claim',
  'establish_notify_release',
  'establish_pending',
  'establish_propose',
  'establish_stage_document',
  'establish_submit',
  'execute',
  'health',
  'job_cancel',
  'job_claim',
  'job_create',
  'job_heartbeat',
  'job_idem_begin',
  'job_idem_complete',
  'job_list',
  'job_list_claimable',
  'job_read',
  'job_record',
  // ss#2614 routine 11: the chronology-package job seam. Bodies live in
  // operator/workspace_broker/medchron_verbs.py; gating per verb is documented
  // there (submit: gateway or root; record: root only).
  'medchron_allowance',
  'medchron_job_list',
  'medchron_job_record',
  'medchron_job_status',
  'medchron_job_submit',
  'ops_ask_sent',
  'ops_propose',
  'ops_resolve',
  'suppressed_wake_append',
  'webhook_suppressed_append',
]

/**
 * Verbs with no mention in the broker test suite as of 2026-08-24.
 *
 * THIS LIST MAY ONLY SHRINK. A verb leaves it by acquiring a test; nothing may
 * join it. The test below enforces both directions — an entry that no longer
 * needs the exemption fails just as loudly as a new verb that wants one, so
 * the list tracks reality downward instead of quietly becoming a permanent
 * amnesty.
 */
const UNTESTED_VERBS = new Set([
  'health',
  'job_cancel',
  'job_heartbeat',
  'job_list',
  'job_list_claimable',
])

function dispatchVerbs(): string[] {
  const src = readFileSync(SERVER, 'utf-8')
  const re = /action == "([a-z_]+)"/g
  const found = new Set<string>()
  let m: RegExpExecArray | null
  while ((m = re.exec(src)) !== null) found.add(m[1])
  return [...found].sort()
}

function testSuiteText(): string {
  const parts: string[] = []
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry)
      if (statSync(full).isDirectory()) {
        if (entry === '__pycache__') continue
        walk(full)
      } else if (entry.endsWith('.py')) {
        parts.push(readFileSync(full, 'utf-8'))
      }
    }
  }
  walk(TESTS_DIR)
  return parts.join('\n')
}

describe('workspace broker verb registry', () => {
  it('the extractor finds a real dispatch surface', () => {
    // Law 12 on the instrument. "Every verb is tested" is trivially true of an
    // empty verb set, so the floor is asserted before anything is concluded
    // from the set's contents.
    expect(dispatchVerbs().length).toBeGreaterThanOrEqual(25)
    expect(testSuiteText().length).toBeGreaterThan(1000)
  })

  it('the dispatch surface matches the registry exactly', () => {
    const actual = dispatchVerbs()
    const added = actual.filter((v) => !EXPECTED_VERBS.includes(v))
    const removed = EXPECTED_VERBS.filter((v) => !actual.includes(v))

    expect(
      actual,
      `The broker's verb surface changed.\n` +
        `Added: ${added.join(', ') || '(none)'}\n` +
        `Removed: ${removed.join(', ') || '(none)'}\n` +
        `Every verb is a uid-gated door into the append-only audit log, and a WRITING verb ` +
        `must pin exactly one action_type so it cannot forge another verb's row. Update ` +
        `EXPECTED_VERBS in this file in the same PR, so the addition is something a reviewer ` +
        `sees rather than something a dispatcher edit does quietly.`
    ).toEqual([...EXPECTED_VERBS].sort())
  })

  it('every verb is named in the broker test suite, and the exemption list only shrinks', () => {
    const suite = testSuiteText()
    const mentioned = (verb: string): boolean =>
      suite.includes(`"${verb}"`) || suite.includes(`'${verb}'`)

    const newlyUnmentioned = dispatchVerbs().filter((v) => !mentioned(v) && !UNTESTED_VERBS.has(v))
    expect(
      newlyUnmentioned,
      `These verbs are dispatched by the broker and appear in no test: ` +
        `${newlyUnmentioned.join(', ')}. Add a test that exercises the verb. ` +
        `Do not add it to UNTESTED_VERBS — that list is frozen debt from 2026-08-24 and ` +
        `may only shrink.`
    ).toEqual([])

    const nowCovered = [...UNTESTED_VERBS].filter(mentioned)
    expect(
      nowCovered,
      `These verbs are on the UNTESTED_VERBS exemption list but now HAVE a test: ` +
        `${nowCovered.join(', ')}. Remove them from the list so the ratchet keeps its ` +
        `new, tighter position.`
    ).toEqual([])
  })
})
