/**
 * Typography drift guard: font families are declared in exactly one place.
 *
 * The canonical system (Captain ruling 2026-07-06) is two families:
 * Archivo (display + body) and JetBrains Mono (eyebrows, labels, chips,
 * table headers, fixed-width data). Archivo Narrow is retired.
 *
 * Families reach markup only through the semantic utilities generated by
 * the @theme block in src/styles/global.css (font-display / font-body /
 * font-mono) or through the --ss-font-* CSS variables. Hand-typed
 * Tailwind arbitrary values like font-['Archivo_Narrow'] are what let
 * marketing, admin, and portal drift into separate de-facto systems
 * (the /agent defect fixed in #1757), so they are banned outright.
 *
 * The Google Fonts stylesheet URL is likewise declared once, in
 * src/lib/fonts.ts (GOOGLE_FONTS_URL), so the loaded family set cannot
 * fork per page.
 *
 * Deliberately out of scope: src/lib/email/ (inline-styled HTML email)
 * and src/lib/pdf/ (react-pdf registered fonts on signed documents).
 */

import { describe, it, expect } from 'vitest'
import { readdirSync, readFileSync, statSync } from 'fs'
import { resolve, join, extname, relative } from 'path'

const SRC_ROOT = resolve('src')

/** The one module allowed to declare a Google Fonts URL. */
const FONTS_MODULE = resolve('src/lib/fonts.ts')

/** Surfaces with their own font constraints, exempt from these rules. */
const EXCLUDED_DIRS = [resolve('src/lib/email'), resolve('src/lib/pdf')]

/** Inline-styled HTML email authored outside src/lib/email/. */
const EXCLUDED_FILES = ['lib/booking/alerts.ts']

function isWithinDir(path: string, dir: string): boolean {
  return path === dir || path.startsWith(`${dir}/`)
}

function collectFiles(dir: string, exts: string[]): string[] {
  const files: string[] = []
  for (const entry of readdirSync(dir)) {
    // Test-time walk of a hardcoded repo directory; no user input.
    // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
    const fullPath = join(dir, entry)
    if (EXCLUDED_DIRS.some((excluded) => isWithinDir(fullPath, excluded))) continue
    if (EXCLUDED_FILES.includes(relative(SRC_ROOT, fullPath))) continue
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      files.push(...collectFiles(fullPath, exts))
    } else if (
      exts.includes(extname(entry)) &&
      !entry.endsWith('.test.ts') &&
      !entry.endsWith('.test.tsx')
    ) {
      files.push(fullPath)
    }
  }
  return files
}

function offenders(files: string[], pattern: RegExp): string[] {
  const hits: string[] = []
  for (const file of files) {
    const content = readFileSync(file, 'utf-8')
    const lines = content.split('\n')
    lines.forEach((line, i) => {
      if (pattern.test(line)) hits.push(`${relative(process.cwd(), file)}:${i + 1}: ${line.trim()}`)
    })
  }
  return hits
}

describe('typography token guard', () => {
  const sourceFiles = collectFiles(SRC_ROOT, ['.astro', '.ts', '.tsx', '.css', '.jsx'])

  it('bans Tailwind arbitrary font-family literals (use font-body / font-display / font-mono)', () => {
    const hits = offenders(sourceFiles, /font-\[['"]/)
    expect(hits, `Raw font-['...'] literals found:\n${hits.join('\n')}`).toEqual([])
  })

  it('bans the retired Archivo Narrow family everywhere in src/', () => {
    // Matches CSS declarations, Tailwind literals, and Google Fonts URL
    // segments. Prose mentions in comments are also banned so docs cannot
    // describe a register that no longer exists (the historical note in
    // global.css and src/lib/fonts.ts marks the retirement itself).
    const hits = offenders(sourceFiles, /Archivo[ _+]Narrow/).filter(
      (hit) => !hit.includes('retired')
    )
    expect(hits, `Archivo Narrow is retired but still referenced:\n${hits.join('\n')}`).toEqual([])
  })

  it('bans hardcoded Google Fonts URLs outside src/lib/fonts.ts', () => {
    // Static path comparison against a repo constant; no user input.
    // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
    const files = sourceFiles.filter((f) => resolve(f) !== FONTS_MODULE)
    const hits = offenders(files, /fonts\.googleapis\.com\/css2\?family=(?!Material)/)
    expect(
      hits,
      `Hardcoded font stylesheet URLs found (import GOOGLE_FONTS_URL from src/lib/fonts instead):\n${hits.join('\n')}`
    ).toEqual([])
  })

  it('bans raw font-family family names in style blocks (use var(--ss-font-*))', () => {
    // Any font-family declaration in src that names a family directly
    // rather than referencing a token. Material Symbols is the icon font
    // and global.css is the definition point.
    // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
    const files = sourceFiles.filter((f) => resolve(f) !== resolve('src/styles/global.css'))
    const hits = offenders(files, /font-family:\s*['"](?!Material Symbols)/)
    expect(
      hits,
      `Raw font-family declarations found (use var(--ss-font-*)):\n${hits.join('\n')}`
    ).toEqual([])
  })
})
