-- ============================================================================
-- Migration 0002: audit_log indexes for persistence layer (issue #891)
-- ============================================================================
--
-- Issue #891 acceptance criteria call for the audit_log table to be indexed
-- by timestamp, customer, skill, and action class so that the writer module
-- (operator/adapter/audit_log.py) and any downstream readers can satisfy
-- the per-customer compliance-evidence queries documented in
-- compliance-evidence-packet.md without scanning the full table.
--
-- Note on the customer dimension. The audit_log lives in the per-customer
-- D1 database (hermes-{slug}-d1) per ADR 0008 (customer-owned memory
-- artifact). There is no row-level customer column because cross-customer
-- queries are forbidden by ADR 0009 (cross-machine query prohibition). The
-- "indexed by customer" criterion is satisfied at the database-binding
-- layer — one D1 binding per customer Machine — not at the SQL index layer.
--
-- The migration in 0001 created three indexes:
--   - idx_audit_ts ON audit_log(ts)
--   - idx_audit_action_type ON audit_log(action_type, ts)
--   - idx_audit_actor ON audit_log(actor, ts)
--
-- This migration adds:
--   - idx_audit_ts_desc — timestamp DESC for newest-first listing (the
--     primary read pattern for the dashboard recent-activity feed)
--   - idx_audit_skill — by skill_name + ts DESC so per-skill audit drills
--     are point queries, not full scans
--   - idx_audit_action_class — by action_type + ts DESC for the
--     compliance-evidence packet generator which buckets by action class
--
-- Forward-only: no drops on the existing indexes; they continue to serve
-- queries that filter without an order direction.
--
-- ============================================================================
-- Logpush configuration plan (deferred to Hermes deployment layer)
-- ============================================================================
--
-- AC: "Backed up via Logpush (separate retention path)"
--
-- Logpush is configured on the Worker that hosts the per-customer Hermes
-- Machine, not on this portal repo's Worker (ss-web). The configuration
-- lives in the Hermes-side wrangler.toml during Phase A.5 deployment and
-- is not in this repo's scope. Documenting the required config here so
-- the operator who provisions the customer Worker knows what to set up:
--
-- 1. Enable D1 query logs on the per-customer database via the Cloudflare
--    dashboard:  Workers & Pages -> D1 -> hermes-{slug}-d1 -> Logs.
--
-- 2. Create a Logpush job that filters for audit_log INSERT statements and
--    delivers them to a long-retention destination separate from D1 (R2
--    bucket smd-audit-archive/{customer}/, S3, or Logflare). Recommended
--    destination: R2 with bucket-level Object Lock so backed-up audit
--    rows cannot be modified or deleted even by Cloudflare account admins.
--
--    Example wrangler.toml fragment to add on the Hermes deployment side:
--
--      [[d1_databases]]
--      binding = "DB"
--      database_name = "hermes-{slug}-d1"
--      database_id = "<id>"
--
--      [[r2_buckets]]
--      binding = "AUDIT_ARCHIVE"
--      bucket_name = "smd-audit-archive-{slug}"
--
--    The Worker code mirrors each INSERT into R2 keyed by
--    {YYYY}/{MM}/{DD}/{ulid}.json. Object lock is configured via the R2
--    dashboard (Compliance Mode, retention period = 7 years for legal
--    matters, 1 year for marketing customers).
--
-- 3. Retention policies:
--    - D1 row: indefinite (immutability enforced at app layer per d1-schema.md)
--    - R2 mirror: per-vertical (law=7y, default=3y)
--    - Logpush stream: 30 days (operational replay only)
--
-- 4. Verification: after each customer provision, run a smoke test that
--    inserts an audit row, sleeps 60s, and confirms the R2 mirror object
--    exists. Provisioner exits non-zero if missing.
--
-- This block is documentation only — no SQL side effects. The provisioner
-- script for the Hermes Worker is owned by issue #800 follow-on work.
-- ============================================================================

-- Newest-first listing (dashboard recent-activity feed primary path)
CREATE INDEX IF NOT EXISTS idx_audit_ts_desc ON audit_log(ts DESC);

-- Per-skill drill (compliance + dashboard skill-detail views)
CREATE INDEX IF NOT EXISTS idx_audit_skill ON audit_log(skill_name, ts DESC);

-- Per-action-class bucket (compliance-evidence packet generator)
CREATE INDEX IF NOT EXISTS idx_audit_action_class ON audit_log(action_type, ts DESC);

-- Bump user_version. 0001 set it to 1; this is migration 2.
PRAGMA user_version = 2;
