#!/usr/bin/env bash
# Claims probe — generated by /code-review v2.
#
# Every fact re-derives itself. Two fields govern how a result is read:
#   state:     OPEN  = defect still stands   | FIXED = defect was fixed
#   direction: exact | at-most | at-least    (which way is improvement)
#
#   HOLDS + FIXED -> closed, skipped next run
#   HOLDS + OPEN  -> STILL-OPEN, carried into every report, never skipped
#   DRIFT + FIXED -> regression, loud
#   DRIFT + OPEN  -> improvement or change, re-measure
#
# Usage: bash docs/reviews/claims-2026-08-25.probe.sh
# Exit:  0 = nothing regressed, 1 = a FIXED claim broke or a shape check failed

cd "$(dirname "$0")/../.." || exit 2

pass=0; still_open=0; regressed=0; drift=0
REPORT="docs/reviews/claims-2026-08-25.md"

# ---------------------------------------------------------------- self-check
# The deliverable polices its own shape, so "report under 60 lines" is a control
# rather than an intention. v1's failure was self-assessment of self-authored
# output; a number cannot be talked past.
if [ -f "$REPORT" ]; then
  lines=$(grep -cve '^[[:space:]]*$' "$REPORT")
  grades=$(grep -cE '^\| [A-F][+-]? ' "$REPORT" || true)
  [ "$lines" -le 60 ] || { echo "SHAPE FAIL: report is $lines non-blank lines (max 60)"; exit 1; }
  [ "$grades" -eq 0 ] || { echo "SHAPE FAIL: report contains $grades letter-grade rows"; exit 1; }
  printf '  shape: %s non-blank lines, %s grade rows\n\n' "$lines" "$grades"
fi

# ------------------------------------------------------------------- checker
check() {
  local id="$1" state="$2" dir="$3" expected="$4" actual="$5" desc="$6"
  local ok=1
  case "$dir" in
    exact)    [ "$actual" = "$expected" ] || ok=0 ;;
    at-most)  [ "$actual" -le "$expected" ] 2>/dev/null || ok=0 ;;
    at-least) [ "$actual" -ge "$expected" ] 2>/dev/null || ok=0 ;;
  esac

  if [ "$ok" = 1 ] && [ "$state" = "FIXED" ]; then
    printf '  \033[32mHOLDS     \033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; pass=$((pass+1))
  elif [ "$ok" = 1 ] && [ "$state" = "OPEN" ]; then
    printf '  \033[33mSTILL-OPEN\033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; still_open=$((still_open+1))
  elif [ "$state" = "FIXED" ]; then
    printf '  \033[31mREGRESSED \033[0m %-5s %s expected %s %s, got %s\n' "$id" "$desc" "$dir" "$expected" "$actual"; regressed=$((regressed+1))
  else
    printf '  \033[36mCHANGED   \033[0m %-5s %s was %s %s, now %s — re-measure\n' "$id" "$desc" "$dir" "$expected" "$actual"; drift=$((drift+1))
  fi
}

echo "Claims for ss-console, 2026-08-25"
echo

# ============================================================ ABSENCE LANE ===
# A6: no security response headers anywhere in shipped code.
#
# POSITIVE CONTROL (PC6) is what the 2026-08-23 review lacked. "0 matches" is
# only evidence if the instrument could have returned non-zero — same regex,
# same paths, same flags, on a term that IS present. Without it the finding is
# inadmissible, not merely low-confidence.
pc6=$(grep -rniE "content-type|cache-control" src/ workers/ public/ wrangler.toml 2>/dev/null | wc -l | tr -d ' ')
check PC6 FIXED at-least 1 "$pc6" "instrument is live (sibling header terms found)"

a6=$(grep -rniE "content-security-policy|x-frame-options|strict-transport-security|frame-ancestors" \
       src/ workers/ public/ wrangler.toml 2>/dev/null | wc -l | tr -d ' ')
check A6 OPEN exact 0 "$a6" "no security response headers set anywhere"

# ============================================================== INVARIANTS ===
check F1  OPEN at-most  2   "$(grep -rn 'sticky_stop\|record_tool_failure\|record_refusal' operator/ --include='*.py' 2>/dev/null | grep -v test | grep -v control-probes | grep -v 'sticky_stop.py:' | wc -l | tr -d ' ')" "sticky_stop has no code callers"
check F3  OPEN exact    0   "$(grep -rln '_VERBS' operator/workspace_broker/tests/ 2>/dev/null | wc -l | tr -d ' ')" "no test enumerates broker verbs"
check F4  OPEN exact    0   "$(grep -o '\"[a-z_/]*\.py\"' operator/contracts/overlay-pairs.json 2>/dev/null | sort -u | grep -c trust_ceiling | tr -d ' ')" "trust_ceiling absent from parity manifest"
check F7  OPEN at-most  4   "$(grep -rln 'class BrokerSuppressedWakeWriter' operator/skills/ 2>/dev/null | wc -l | tr -d ' ')" "BrokerSuppressedWakeWriter copies"
check F9  OPEN at-most  28  "$(grep -rn 'sys.path.insert' operator/ --include='*.py' 2>/dev/null | grep -v test | wc -l | tr -d ' ')" "sys.path.insert stands in for packaging"
check F12 OPEN exact    0   "$(grep -rn 'test:coverage\|--coverage' .github/workflows/ 2>/dev/null | wc -l | tr -d ' ')" "no workflow runs coverage"

# ================================================================== FIXED ====
check F15 FIXED at-least 3  "$(grep -c 'redactOpaqueSegments' src/pages/api/events.ts 2>/dev/null | tr -d ' ')" "manage-token redaction wired"
check F17 FIXED at-least 1  "$(grep -c '{!disableAnalytics && <EventsTracker />}' src/layouts/Base.astro 2>/dev/null | tr -d ' ')" "EventsTracker honours disableAnalytics"

echo
echo "  $pass closed · $still_open still open · $regressed regressed · $drift changed"
[ "$regressed" -eq 0 ] || exit 1
exit 0
